var spaceThings = [
    {
        name:'Moon',
        distance:5,
        width:220,
        height:220,
        img:'spacestuff/moon.jpg'
    },
    {
        name:'Mars',
        distance:20,
        width:640,
        height:524,
        img:'spacestuff/mars.jpg'
    },
    {
        name:'Asteroid Belt',
        distance:40,
        run:function(el) {
            
        }
    }
    {
        name:'Jupiter',
        distance:80,
        width:640,
        height:524,
        img:'spacestuff/jupiter.jpg'
    },
    {
        name:'Saturn',
        distance:100,
        width:640,
        height:395,
        img:'spacestuff/saturn.jpg'
    },
    {
        name:'Uranus',
        distance:150,
        width:970,
        height:1000,
        img:'spacestuff/uranus.jpg'
    },
    {
        name:'Neptune',
        distance:180,
        width:600,
        height:588,
        img:'spacestuff/neptune.jpg'
    }
];